"""add notification metadata

Revision ID: 014460c96037
Revises: 426e80087e8b
Create Date: 2026-06-07 15:23:04.060633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '014460c96037'
down_revision = '426e80087e8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_type', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('receiver_role', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('url', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('opened', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('opened')
        batch_op.drop_column('url')
        batch_op.drop_column('title')
        batch_op.drop_column('receiver_role')
        batch_op.drop_column('notification_type')

    # ### end Alembic commands ###
