"""add agent solutions

Revision ID: 1138003a1926
Revises: b2ec53858b2b
Create Date: 2026-06-04 12:11:55.056835

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1138003a1926'
down_revision = 'b2ec53858b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_solutions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('view_count',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('reuse_count',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('agent_solutions_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tickets', ['ticket_id'], ['id'])
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_solutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('agent_solutions_ibfk_3'), 'tickets', ['ticket_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('reuse_count',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('view_count',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
