"""add waiting customer reminder fields

Revision ID: 118f0c317f9d
Revises: b69737649f68
Create Date: 2026-06-06 16:05:12.884295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118f0c317f9d'
down_revision = 'b69737649f68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unassigned_15min_sent', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('unassigned_30min_sent', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('unassigned_30min_sent')
        batch_op.drop_column('unassigned_15min_sent')

    # ### end Alembic commands ###
