"""add chatbot settings

Revision ID: 22c3a953c0d6
Revises: 5362c66c1362
Create Date: 2026-05-30 22:14:08.454961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c3a953c0d6'
down_revision = '5362c66c1362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_enabled', sa.Boolean(), nullable=False),
    sa.Column('fallback_message', sa.Text(), nullable=False),
    sa.Column('auto_escalation_enabled', sa.Boolean(), nullable=False),
    sa.Column('escalation_keywords', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatbot_settings')
    # ### end Alembic commands ###
