"""add chatbot review fields

Revision ID: 32507b0420e9
Revises: 22c3a953c0d6
Create Date: 2026-05-30 22:54:00.069879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32507b0420e9'
down_revision = '22c3a953c0d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['reviewed_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by_id')
        batch_op.drop_column('review_status')

    # ### end Alembic commands ###
