"""add resolution status to chat messages

Revision ID: 4b7f738d5860
Revises: a2200b99e0ae
Create Date: 2026-06-02 19:14:13.487415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b7f738d5860'
down_revision = 'a2200b99e0ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolution_status', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('resolution_status')

    # ### end Alembic commands ###
