"""allow agent report notifications

Revision ID: 5362c66c1362
Revises: 6c8bb99ba1ab
Create Date: 2026-05-30 20:32:52.337573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5362c66c1362'
down_revision = '6c8bb99ba1ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_report_id', sa.Integer(), nullable=True))
        batch_op.alter_column('ticket_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'agent_reports', ['agent_report_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('ticket_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('agent_report_id')

    # ### end Alembic commands ###
