"""add advanced ai settings

Revision ID: 63615a093ea3
Revises: 1138003a1926
Create Date: 2026-06-04 13:03:19.973206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63615a093ea3'
down_revision = '1138003a1926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chatbot_tone', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('response_length', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('confidence_threshold', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('system_prompt', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot_settings', schema=None) as batch_op:
        batch_op.drop_column('system_prompt')
        batch_op.drop_column('confidence_threshold')
        batch_op.drop_column('response_length')
        batch_op.drop_column('chatbot_tone')

    # ### end Alembic commands ###
