"""add attachments to agent reports

Revision ID: 6c8bb99ba1ab
Revises: fcf98af9f526
Create Date: 2026-05-30 18:48:42.089749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c8bb99ba1ab'
down_revision = 'fcf98af9f526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orig_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('file_link', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_reports', schema=None) as batch_op:
        batch_op.drop_column('file_link')
        batch_op.drop_column('orig_file')

    # ### end Alembic commands ###
