"""add customer visible to chat messages

Revision ID: a2200b99e0ae
Revises: 32507b0420e9
Create Date: 2026-06-02 18:57:34.006120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2200b99e0ae'
down_revision = '32507b0420e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_visible', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('customer_visible')

    # ### end Alembic commands ###
