"""add waiting customer reminder fields

Revision ID: b69737649f68
Revises: 63615a093ea3
Create Date: 2026-06-06 14:56:42.089990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b69737649f68'
down_revision = '63615a093ea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waiting_customer_since', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('inactive_reminder_sent', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('inactive_reminder_sent')
        batch_op.drop_column('waiting_customer_since')

    # ### end Alembic commands ###
