"""add view count to faq and knowledge article

Revision ID: bc5be2562726
Revises: 3e1106ec6335
Create Date: 2026-06-04 11:49:24.372181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc5be2562726'
down_revision = '3e1106ec6335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faqs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view_count', sa.Integer(), nullable=False))

    with op.batch_alter_table('knowledge_articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_articles', schema=None) as batch_op:
        batch_op.drop_column('view_count')

    with op.batch_alter_table('faqs', schema=None) as batch_op:
        batch_op.drop_column('view_count')

    # ### end Alembic commands ###
