"""upgrade chatbot logs

Revision ID: da2e25c4bbd4
Revises: f471a7051fb1
Create Date: 2026-05-25 16:27:41.522915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da2e25c4bbd4'
down_revision = 'f471a7051fb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faq_matched', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ai_used', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('escalated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('guest_user', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('guest_user')
        batch_op.drop_column('escalated')
        batch_op.drop_column('ai_used')
        batch_op.drop_column('faq_matched')

    # ### end Alembic commands ###
