"""multi user model fixes

Revision ID: e84364f1dc0b
Revises: 014460c96037
Create Date: 2026-06-14 21:09:25.347899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e84364f1dc0b'
down_revision = '014460c96037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_solutions', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['ticket_id'])
        batch_op.drop_constraint(batch_op.f('agent_solutions_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tickets', ['ticket_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_id', sa.Integer(), nullable=True))
        batch_op.create_index('idx_chat_ticket', ['ticket_id'], unique=False)
        batch_op.create_index('idx_chat_user_resolution', ['user_id', 'resolution_status'], unique=False)
        batch_op.create_index('idx_chat_user_visible', ['user_id', 'customer_visible'], unique=False)
        batch_op.create_foreign_key(None, 'tickets', ['ticket_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index('idx_comment_ticket_created', ['ticket_id', 'created_at'], unique=False)

    with op.batch_alter_table('customer_satisfaction', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_ticket_customer_rating', ['ticket_id', 'customer_id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('sender_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_index('idx_notification_receiver_created', ['receiver_id', 'created_at'], unique=False)
        batch_op.create_index('idx_notification_receiver_seen', ['receiver_id', 'seen'], unique=False)

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index('idx_ticket_author_status', ['author_id', 'status_id'], unique=False)
        batch_op.create_index('idx_ticket_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_ticket_owner_status', ['owner_id', 'status_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index('idx_ticket_owner_status')
        batch_op.drop_index('idx_ticket_created_at')
        batch_op.drop_index('idx_ticket_author_status')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('idx_notification_receiver_seen')
        batch_op.drop_index('idx_notification_receiver_created')
        batch_op.alter_column('sender_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('customer_satisfaction', schema=None) as batch_op:
        batch_op.drop_constraint('uq_ticket_customer_rating', type_='unique')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index('idx_comment_ticket_created')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_chat_user_visible')
        batch_op.drop_index('idx_chat_user_resolution')
        batch_op.drop_index('idx_chat_ticket')
        batch_op.drop_column('ticket_id')

    with op.batch_alter_table('agent_solutions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('agent_solutions_ibfk_3'), 'tickets', ['ticket_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
